### PR TITLE
Adding three housing images

### PR DESCRIPTION
**Pull request by Augusta02**
I added one bungalow and two storey building images

### CODE REVIEW

**Review by Sammybams — CHANGES_REQUESTED** [review]
Thank you @Augusta02. Very clear pictures. Though we would not be able to merge this as we would prefer a minimum of 10 new images. And also you have some extra files that have been committed along with the images which are default files created by the macOS in folders (.DS_Store).

Try to delete these files and add more images and we would be very happy to merge your pull request. Thank you.

**Comment by Augusta02** [comment]
Thank you, I will make corrections

**Review by Sammybams — CHANGES_REQUESTED** [review]
Hello @Augusta02, great additions.  But it seems you have wrongly classified the image Project_1/Data/Storey-building/au_storey.jpeg as a storey building instead of high-rise. Note that high-rise isn't only skyscrapers. That image has the properties of a high-rise than a storey building. Also the .DS_Store files are still there.

I'll close this pull request so you can make the changes and revert.

**Review by Sammybams — APPROVED** [review]
Thank you @Augusta02. Great additions.

**Pull request merged**
