### PR TITLE
adding buildings

### PR DESCRIPTION
**Pull request by Ajlightpro**
dings

### CODE REVIEW

**Review by Sammybams — CHANGES_REQUESTED** [review]
Thank you very much @Ajlightpro. These contributions are appreciated. But there are some wrongfully classified bungalows which are meant to be storey buildings.  Please kindly review and make changes and we would be happy to merge your pull request.

**Comment by Ajlightpro** [comment]
All right I’ll make changes

**Comment by Sammybams** [comment]
Alright @Ajlightpro, we'll be expecting.

**Comment by Ajlightpro** [comment]
Could you please add the high rise and story building, so I will know am
left to push the bungalow sir.?

**Comment by Sammybams** [comment]
Alright. Don't bother @Ajlightpro. We'll fix the mixup from our end.

**Comment by Ajlightpro** [comment]
Ok, thanks.

**Review by Sammybams — APPROVED** [review]
Thank you @Ajlightpro. The mix up will be sorted from our end. You don't need to change anything.

**Pull request merged**
