### PR TITLE
Modification in images

### PR DESCRIPTION
**Pull request by anushka9555**
Modified the images to the required aspect ratio.

### CODE REVIEW

**Comment by anushka9555** [comment]
Hi @Sammybams I tried changing the aspect ratio and created a new PR. Please check if it is fine. Since I am new to open source I don't have much idea about the things now. Sorry for any inconvenience.

**Review by Sammybams — CHANGES_REQUESTED** [review]
Thank you very much @an for your contribution.
It also seems you have not correctly categorized the buildings.

Project_1/Data/Bungalow/Zanu_Bunglow.jpeg should be a storey building.
Project_1/Data/Bungalow/Zanu_bunglow_1.jpeg should be a storey building.
Project_1/Data/Bungalow/Zanu_bunglow_3.jpegshoud be a storey building.

Project_1/Data/High-rise/Zanu_high_rise.jpeg isn't a high-rise building and is more like a storey building.
Project_1/Data/High-rise/Zanu_high_rise_1.jpg is a storey building.

Please effect this changes and then we would be happy to merge your pull request. Thank you very much.

**Comment by anushka9555** [comment]
Hi @Sammybams. Done the changes

**Review by Sammybams — APPROVED** [review]
Thank you very much @anushka9555.

**Comment by Sammybams** [comment]
Alright @anushka9555.

**Pull request merged**
