### PR TITLE
Victor Umunna Image classification file

### PR DESCRIPTION
**Pull request by VictorUmunna**

### CODE REVIEW

**Review by Sammybams — COMMENTED** [review]
Thank you @VictorUmunna but we cannot merge this pull request as it has to be contributing to something definite to any of the projects.

**Comment by VictorUmunna** [comment]
Pease what do you mean by that? From the Contribution.md file, you suggest we create a folder and run our own image classification. How am I not contributing to 'something definite?'

**Comment by Sammybams** [comment]
> Pease what do you mean by that? From the Contribution.md file, you suggest we create a folder and run our own image classification. How am I not contributing to 'something definite?'

Hello @VictorUmunna. My sincere apologies for the mixup. I wasn't able to view your file then, so I made an assumption that you were just setting up your notebook. I have gone through it now and it will be merged. Thank you for the feedback.

**Review by Sammybams — APPROVED** [review]
Thank you very much @VictorUmunna for this contribution. It is indeed great step in building the image classification project.

**Pull request merged**
