### PR TITLE
Image_Classification_Folder

### PR DESCRIPTION
**Pull request by Tosinkuzzy**
Contributing to cutting-edge open-source projects. 
My first contribution to this project is getting dependacies, terminal and notebook set up.
My second contribution is renaming the image_classification_to_my_username which was stated in Project_1.

I want to implement more and keep on learning from others.

### CODE REVIEW

**Review by Sammybams — CHANGES_REQUESTED** [review]
Thank you @Tosinkuzzy for your contribution. However, this cannot be merged. The instruction is to create your own folder following the naming convention as provided in the [contribution guidelines](https://github.com/mlsanigeria/AI-Hacktober-MLSA/blob/main/CONTRIBUTING.md) and as you would have seen from other folders within project 1 that have been created. And not to rename that particular folder.

Thank you very much.

**Comment by Sammybams** [comment]
> Contributing to cutting-edge open-source projects. My first contribution to this project is getting dependacies, terminal and notebook set up. My second contribution is renaming the image_classification_to_my_username which was stated in Project_1.
> 
> I want to implement more and keep on learning from others.

@Tosinkuzzy, We would also like to bring to your notice that you can't really make any contributions towards Project 1 apart from the image collection process. You can set up your notebook for modelling, but it has to come along with something else that has definite relevance to the progress of the project (for example, the image collection).

Thank you very much.

**Comment by Tosinkuzzy** [comment]
Thank you @sammybams for the quick response. i got it fixed.

**Review by Sammybams — CHANGES_REQUESTED** [review]
Hi @Tosinkuzzy, we would also like to bring to your notice that you can't really make any contributions towards Project 1 at the moment apart from the image collection process. When we have accumulated enough data, we would make an announcement that modelling can now begin. You can set up your notebook for modelling, but it has to come along with something else that has definite relevance to the progress of any of the projects (for example in project 1, the image collection).

Thank you very much.

**Pull request closed without merging**
